### ISSUE TITLE
weird spacing

### ISSUE THREAD

**Issue by joelpick** [EIvimeyCook/MetaScreen#2]
For some reason the highlighted words are now on a separate line?

Also whatever is selected to display is inline with the abstract rather than the what it is (e.g. title, authors etc)

**Comment by EIvimeyCook** [comment]
hmmm i cant seem to recreate this! Maybe its browser specific? 

![Screenshot 2024-04-09 at 12 08 58](https://github.com/EIvimeyCook/metRscreen/assets/37153494/f4abf9c9-7f27-4e0d-a2e5-9c216d133831)

**Comment by EIvimeyCook** [comment]
Yeh still not sure how to resolve this - doesnt appear on my version or my browser in R or Edge.

**Comment by EIvimeyCook** [comment]
solved - seemed to be an issue with the latest version of shiny
