### ISSUE TITLE
re - opening past csv

### ISSUE THREAD

**Issue by joelpick** [EIvimeyCook/MetaScreen#4]
it starts loads onto on the first paper

it doesn't appear to load my previous decision or my previous settings

**Comment by EIvimeyCook** [comment]
aaah, because you havent loaded the save file settings. Admittedly, the metRDS file doesnt sound obvious. But if you load that it will - need to change the action buttons to check boxes otherwise it wont be able to record your previous decisions.

**Comment by EIvimeyCook** [comment]
added now - automatically loads past decisions and previous settings
